### ISSUE TITLE
Failed to validate a workflow definition that uses authentication definitions

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/sdk-net#40]
**What happened**:

When creating a new workflow definition, the server returns a DSL validation error similar to:

```
Failed to find an authentication definition with name 'myAuthDef'
```

**What you expected to happen**:

The definition gets successfully created

**How to reproduce it**:

Attempt to create any workflow definition defining a function referencing an authentication definition, like so:

```yaml
...
auth:
- name: myAuthDef
  scheme: basic
  properties:
    username: coolusername
    password: securedpassword
functions:
- name: testFunction
  type: rest
  operation: https://test.com#test
  authRef: myAuthDef
...
```
